collections:

  - name: ansible.posix

  - name: ansible.tower

  - name: ansible.netcommon

  - name: google.cloud

  - name: community.kubernetes
    source: https://towerpah.shadowman.dev/api/galaxy/content/community/

  - name: community.general
    source: https://towerpah.shadowman.dev/api/galaxy/content/community/
  