- name: Install Datadog Agent
  hosts: all
  gather_facts: false

  vars:
    datadog_agent_version: "7.16.0"
    datadog_config:
      hostname: "{{ ansible_fqdn }}"
      log_level: INFO
      apm_config:
        enabled: true
      logs_enabled: false  # available with Agent v6 and v7
      process_config:
        enabled: "true" # type: string
        scrub_args: true
        custom_sensitive_words: ['consul_token', 'dd_api_key']
      network_config:
        enabled: true

  roles:
    - datadog.dd.agent
