---
- hosts: all
  name: Prep Prometheus to scrape more often on Tower metrics
  gather_facts: false

  tasks:

  - name: Updated prometheus config
    ansible.builtin.template:
      src: templates/prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
    notify: restart_prometheus

  handlers:
    - name: restart_prometheus
      ansible.builtin.service:
        name: prometheus
        state: restarted