---
- name: Install Grafana
  hosts: all

# If issues arise with grafana yum install, then manually install
# update /etc/yum.repos.d/grafana.repo to the info below
# [grafana]
# name=grafana
# baseurl=https://packages.grafana.com/oss/rpm
# repo_gpgcheck=1
# enabled=1
# gpgcheck=1
# gpgkey=https://packages.grafana.com/gpg.key
# sslverify=1
# sslcacert=/etc/pki/tls/certs/ca-bundle.crt
# Then run yum install grafana

  tasks:

    - name: Include grafana role
      ansible.builtin.include_role:
        name: lrk.grafana

    - name: Open Firewalld for grafana
      ansible.posix.firewalld:
        port: 9090/tcp
        permanent: true
        state: enabled
      notify: restart_firewalld

    - name: Open Firewalld for prometheus
      ansible.posix.firewalld:
        port: 3000/tcp
        permanent: true
        state: enabled
      notify: restart_firewalld

  handlers:
    - name: restart_firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted
