---
- name: Install Prometheus Node Exporter
  hosts: all
  vars:
    - prometheus_components:
      - node_exporter
    - nodeexporter_version: 1.2.2

  collections:
    - ansible.posix

  roles:
    - lrk.prometheus

  tasks:

  - name: Open Firewalld for Node Exporter
    ansible.posix.firewalld:
      port: 9100/tcp
      permanent: yes
      state: enabled 
    notify: restart_firewalld

  handlers:
    - name: restart_firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted
