- name: Extract data from Tower
  hosts: all
  gather_facts: false
  connection: local

  collections:
    - ansible.tower
    
  tasks: 
  - name: Extract Tower data
    ansible.tower.tower_export:
      all: yes
    register: output

  - name: Create JSON
    ansible.builtin.debug:
      var: output

