- name: Extract data from Tower
  hosts: all
  gather_facts: false
  connection: local

  collections:
    - ansible.tower
    
  tasks: 
  - name: Extract Tower data
    ansible.tower.tower_export:
      workflow_job_templates: 'all'
    register: results