---
# handlers file for snort-config
- name: Restart snort
  ansible.builtin.service:
    name: snort
    state: restarted
  listen: restart snort

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  listen: restart rsyslog
