---
# tasks file for ansible-role-snort

- name: Package pre-reqs are installed
  ansible.builtin.yum:
    state: present
    name:
      - libdnet
      - libselinux-python3
      - python3-virtualenv
      - python3-setuptools
      - python3-pip

- name: Install idstools
  ansible.builtin.pip:
    name: idstools

- name: Set selinux permissve because of policy issue that breaks snort
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Verify required variable is defined
  ansible.builtin.fail:
    msg: "Required variable 'ids_provider' is not defined"
  when: ids_provider is not defined

- name: Ensure ids_provider is valid
  ansible.builtin.fail:
    msg: "Provided value for 'ids_provider' is not valid, must be one of {{ ids_provider_list }}"
  when: ids_provider not in ids_provider_list

- name: Install ids provider snort
  when: "ids_provider == 'snort'"
  block:

    - name: Install snort and dependent packages - user defined
      ansible.builtin.yum:
        name: "{{ ids_install_pkgs }}"
        state: installed
        disable_gpg_check: true
      when: ids_install_pkgs is defined

    - name: Install snort and dependent packages - defaults
      ansible.builtin.yum:
        name: "{{ ids_install_snort_pkgs }}"
        state: installed
        disable_gpg_check: true

      when: ids_install_pkgs is not defined

    - name: Install pulledpork when specified
      ansible.builtin.yum:
        name: "pulledpork"
        state: installed
      when: ids_install_snort_use_pulledpork

    # This is to work around a packaging problem with upstream snort's rpm install
    - name: Symlink libdnet.1 to libdnet.so.1
      ansible.builtin.file:
        src: /usr/lib64/libdnet.so.1
        dest: /usr/lib64/libdnet.1
        state: link

    - name: Create dynamic rules dir
      ansible.builtin.file:
        path: /usr/local/lib/snort_dynamicrules
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: Install snort systemd service unit file
      ansible.builtin.template:
        src: snort.service.j2
        dest: /etc/systemd/system/snort.service
        owner: root
        group: root
        mode: '0644'
      notify: systemctl daemon-reload

    - name: Install snort sysconfig file
      ansible.builtin.template:
        src: etc_sysconfig_snort.j2
        dest: /etc/sysconfig/snort
        owner: root
        group: root
        mode: '0644'
      notify: systemctl daemon-reload

    - name: Handle ids_install_snort_community_rules_url
      block:
        - name: Get ids_install_snort_community_rules_url rules
          ansible.builtin.get_url:
            url: "{{ ids_install_snort_community_rules_url }}"
            dest: "/tmp/ansible_role_ids_snort_community-rules.tar.gz"
            owner: root
            group: root
            mode: '0644'

        - name: Unpack ids_install_snort_community_rules_url rules
          ansible.builtin.unarchive:
            remote_src: true
            src: "/tmp/ansible_role_ids_snort_community-rules.tar.gz"
            dest: "/etc/snort/"
            creates: "/etc/snort/{{ ids_install_snort_community_rules_subdir }}"

        - name: Check for /etc/snort/community-rules/ from rules
          ansible.builtin.stat:
            path: '/etc/snort/community-rules/'
          register: comm_st

        - name: Grab the list of files in /etc/snort/community-rules/
          ansible.builtin.find:
            paths: '/etc/snort/community-rules/'
            file_type: file
          register: comm_rules_files

        - name: Copy /etc/snort/community-rules/ files from rules into /etc/snort/
          ansible.builtin.copy:
            remote_src: true
            src: '{{ item["path"] }}'
            dest: '/etc/snort/{{ item["path"] | basename }}'
            force: false
            owner: root
            group: root
            mode: '0644'
          loop: "{{ comm_rules_files['files'] }}"
          when:
            - (comm_st.stat.isdir is defined) and comm_st.stat.isdir
            - item != "snort.conf"

        - name: Check for community.rules from rules
          ansible.builtin.stat:
            path: '/etc/snort/community.rules'
          register: commr_st

        - name: Ensure rules dir exists
          ansible.builtin.file:
            path: '/etc/snort/rules'
            state: directory
            owner: root
            group: root
            mode: '0644'

        - name: Copy community.rules into
          ansible.builtin.copy:
            remote_src: true
            src: '/etc/snort/community.rules'
            dest: '/etc/snort/rules/community.rules'
            force: false
            owner: root
            group: root
            mode: '0644'
          when: (commr_st.stat.isdir is defined) and commr_st.stat.exists
      when: >
        (ids_install_snort_community_rules_url is defined) and
          ids_install_snort_community_rules_url | length | int > 0

    # NOTE: Order matters, snort registered rules should "win" over community
    #       rules if/when there is ever a conflict in the content. Always copy
    #       registered content last
    - name: Handle ids_install_snort_registered_rules_url rules
      block:
        - name: Get ids_install_snort_registered_rules_url rules
          ansible.builtin.get_url:
            url: "{{ ids_install_snort_registered_rules_url }}"
            dest: "/tmp/ansible_role_ids_snort_registered_rules.tar.gz"
            owner: root
            group: root
            mode: '0644'

        - name: Unpack ids_install_snort_registered_rules_url rules
          ansible.builtin.unarchive:
            remote_src: true
            src: "/tmp/ansible_role_ids_snort_registered_rules.tar.gz"
            dest: "/etc/snort/"
            creates: "/etc/snort/{{ ids_install_snort_registered_rules_subdir }}"

        - name: Check for /etc/snort/etc/ from rules
          ansible.builtin.stat:
            path: '/etc/snort/etc/'
          register: st

        - name: Grab the list of files in /etc/snort/etc/
          ansible.builtin.find:
            paths: '/etc/snort/etc/'
            file_type: file
          register: reg_rules_files

        - name: Copy /etc/snort/etc/ files from rules into /etc/snort/
          ansible.builtin.copy:
            remote_src: true
            src: '{{ item["path"] }}'
            dest: '/etc/snort/{{ item["path"] | basename }}'
            force: false
            owner: root
            group: root
            mode: '0644'
          loop: "{{ reg_rules_files['files'] }}"
          when:
            - (st.stat.isdir is defined) and st.stat.isdir
            - item != "snort.conf"
      when: >
        (ids_install_snort_registered_rules_url is defined) and
          ids_install_snort_registered_rules_url | length | int > 0

    # FIXME - this is kind of a hack
    - name: Ensure snort required files exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
        modification_time: "preserve"
        access_time: "preserve"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - /etc/snort/rules/white_list.rules
        - /etc/snort/rules/black_list.rules
        - /etc/snort/rules/local.rules

    - name: Block for snort
      block:
        - name: Ensure dirs exist as needed for pulledpork
          ansible.builtin.file:
            path: "/etc/snort/rules/iplists/"
            state: "directory"
            owner: root
            group: root
            mode: '0644'

        - name: Run pulledpork
          ansible.builtin.shell: "/usr/bin/pulledpork -c /etc/pulledpork/pulledpork.conf && /usr/bin/touch /etc/pulledpork/ran_pulled_pork"
          args:
            creates: /etc/pulledpork/ran_pulled_pork
      when: ids_install_snort_use_pulledpork

- name: Configure ids log normalization for provider snort
  when: "ids_provider == 'snort' and ids_install_snort_barnyard2_normalize_logs"
  block:
    # Originally from rmonk copr
    # https://copr.fedorainfracloud.org/coprs/rmonk/Snort-IDS/
    - name: Install barnyard
      ansible.builtin.yum:
        name: "{{ ids_install_snort_barnyard_pkg }}"
        state: installed

    - name: Copy barnyard configuration template
      ansible.builtin.template:
        src: barnyard2.conf.j2
        dest: /etc/snort/barnyard2.conf
        owner: root
        group: root
        mode: '0644'

    - name: Install barnyard2 systemd service unit file
      ansible.builtin.template:
        src: barnyard2.service.j2
        dest: /etc/systemd/system/barnyard2.service
        owner: root
        group: root
        mode: '0644'
      notify: systemctl daemon-reload

    - name: Install barnyard2 sysconfig file
      ansible.builtin.template:
        src: etc_sysconfig_barnyard2.j2
        dest: /etc/sysconfig/barnyard2
        owner: root
        group: root
        mode: '0644'
      notify: systemctl daemon-reload

    - name: Start barnyard2
      ansible.builtin.service:
        name: barnyard2
        state: started
        enabled: true
