---
- name: Send Web Link via E-mail
  community.general.mail:
    host: "{{ EMAIL_HOST }}"
    username: "{{ EMAIL_USERNAME }}"
    password: "{{ EMAIL_PASSWORD }}"
    port: "{{ EMAIL_PORT }}"
    subject: "{{ email_subject }}"
    body: "{{ email_body }}"
    from: tower@shadowman.dev
    to: "{{ to_email }}"
  delegate_to: localhost  