---
# handlers file for ansible-prometheus

- name: Reload prometheus daemon systemd service
  ansible.builtin.systemd:
    name: "{{ prometheus_service_name }}"
    daemon_reload: true
    state: restarted
  listen: "restart prometheus daemon"

- name: Restart prometheus service
  ansible.builtin.service:
    name: "{{ prometheus_service_name }}"
    state: restarted
  listen: "restart prometheus service"

- name: Reload alertmanager daemon systemd service
  ansible.builtin.systemd:
    name: "{{ alertmanager_service_name }}"
    daemon_reload: true
    state: restarted
  listen: "restart alertmanager daemon"

- name: Restart Alert Manager Service
  ansible.builtin.service:
    name: "{{ alertmanager_service_name }}"
    state: restarted
  listen: "restart alertmanager daemon"

- name: Reload node exporter daemon systemd service
  ansible.builtin.systemd:
    name: "{{ nodeexporter_service_name }}"
    daemon_reload: true
    state: restarted
  listen: "reload nodeexporter daemon"

- name: Restart nodeexporter service
  ansible.builtin.service:
    name: "{{ nodeexporter_service_name }}"
    state: restarted
  listen: "restart nodeexporter service"

- name: Restart Firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
  listen: restart_firewalld
