---
- name: Remove agent from Linux
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts.os_family != "Windows"

- name: Remove agent from Windows
  ansible.builtin.include_tasks: windows.yml
  when: ansible_facts.os_family == "Windows"
